#! /usr/bin/env bash
message="*WARNING:* $CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH $CIRCLE_JOB job has failed."

#####
## Announce in Slack channel
#####
# 'color' can be any hex code or the key words 'good', 'warning', or 'danger'
color="danger"

slack_payload=$(
cat <<EOM
{
    "attachments": [
        {
            "fallback": "Required plain-text summary of the attachment.",
            "color": "danger",
            "pretext": "WARNING: $CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH has failed to build!",
            "text": "$CIRCLE_PULL_REQUEST",
            "ts": 123456789
        }
    ]
}
EOM
)

echo
echo "Slack Payload:"
echo "$slack_payload"
echo
echo "Slack url:"
echo "$SLACK_WEBHOOK_URL"
echo