#! /usr/bin/env bash
message="*WARNING:* $CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH $CIRCLE_JOB job has failed."

#####
## Announce in Slack channel
#####
# 'color' can be any hex code or the key words 'good', 'warning', or 'danger'
color="danger"

slack_payload=$(
cat <<EOM
{
    "text": "*WARNING:* $CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH has failed to build"
}
EOM
)

echo
echo "Slack Payload:"
echo "$slack_payload"
echo
echo "Slack url:"
echo "$SLACK_WEBHOOK_URL"
echo
